export const customData: any[] = [
  { subjectScores: 100 },
  { subjectScores: 75 },
  { subjectScores: 120 },
  { subjectScores: 130 },
  { subjectScores: 140 },
  { subjectScores: 250 },
  { subjectScores: 100 },
  { subjectScores: 60 },
  { subjectScores: 5 },
  { subjectScores: 1 },
  { subjectScores: 24 },
  { subjectScores: 25 },
  { subjectScores: 29 },
  { subjectScores: 50 },
];

export const customDataTwo: any[] = [
  { subjectScoresTwo: 250 },
  { subjectScoresTwo: 500 },
  { subjectScoresTwo: 1 },
  { subjectScoresTwo: 250 },
  { subjectScoresTwo: 300 },
  { subjectScoresTwo: 230 },
  { subjectScoresTwo: 450 },
  { subjectScoresTwo: 2 },
  { subjectScoresTwo: 200 },
  { subjectScoresTwo: 10 },
  { subjectScoresTwo: 11 },
  { subjectScoresTwo: 150 },
  { subjectScoresTwo: 400 },
  { subjectScoresTwo: 500 },
  { subjectScoresTwo: 20 },
  { subjectScoresTwo: 50 },
  { subjectScoresTwo: 570 },
  { subjectScoresTwo: 100 },
  { subjectScoresTwo: 250 },
  { subjectScoresTwo: 100 },
  { subjectScoresTwo: 290 },
  { subjectScoresTwo: 200 },
  { subjectScoresTwo: 20 },
  { subjectScoresTwo: 50 },
];

export const combineData: any[] = [
  { subjectScores: 120, subjectScoresTwo: 250 },
  { subjectScores: 110, subjectScoresTwo: 220 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 110, subjectScoresTwo: 100 },
  { subjectScores: 20, subjectScoresTwo: 205 },
  { subjectScores: 10, subjectScoresTwo: 20 },
  { subjectScores: 110, subjectScoresTwo: 145 },
  { subjectScores: 250, subjectScoresTwo: 250 },
  { subjectScores: 10, subjectScoresTwo: 200 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 45, subjectScoresTwo: 22 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 170, subjectScoresTwo: 270 },
  { subjectScores: 23, subjectScoresTwo: 250 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 250, subjectScoresTwo: 280 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 150, subjectScoresTwo: 50 },
  { subjectScores: 100, subjectScoresTwo: 250 },
  { subjectScores: 100, subjectScoresTwo: 250 },
];
